from __future__ import annotations


TRACK_SEED = [
    {
        "id": "pf-international",
        "name": "PF International",
        "venue": "Grantham, Lincolnshire",
        "postcode": "NG32 2AY",
        "address_json": '["PF International Kart Circuit","Grantham","Lincolnshire","NG32 2AY"]',
        "google_query": "PF International Kart Circuit Grantham NG32 2AY",
        "official_url": "https://kartpfi.com/",
        "source_urls_json": '["https://kartpfi.com/","https://kartpfi.com/the-circuit","https://www.kartcom.com/en/places/pf-international/"]',
        "layout_notes": "Fast and flowing with long straights where exit quality carries for a long time.",
        "coaching_focus_json": '["Protect exit speed onto the long straights.","Stay tidy through the bridge and final sector where momentum loss lingers.","Prioritise throttle timing over forcing late entry speed."]',
        "corner_notes_json": '["Heavy braking zones reward calm brake release before rotation.","Fast sweepers punish extra steering input.","Final-sector exits matter more than aggressive entry."]',
        "corner_definitions_json": '[{"name":"Turn 1 Hairpin","sequence":1,"section_type":"hairpin","sector_name":"Sector 1","start_pct":0.03,"end_pct":0.16,"apex_pct":0.09,"note":"Big stop at the end of the straight. Prioritise release and exit."},{"name":"Infield Left","sequence":2,"section_type":"left","sector_name":"Sector 1","start_pct":0.16,"end_pct":0.24,"apex_pct":0.2,"note":"Keep the kart free and avoid pinching the middle phase."},{"name":"Infield Right","sequence":3,"section_type":"right","sector_name":"Sector 1","start_pct":0.24,"end_pct":0.33,"apex_pct":0.29,"note":"Use the left-right as one sequence and keep momentum alive."},{"name":"Bridge Left","sequence":4,"section_type":"sweeper","sector_name":"Sector 2","start_pct":0.33,"end_pct":0.47,"apex_pct":0.4,"note":"Commitment matters here, but extra steering scrub is expensive."},{"name":"Boot Hairpin","sequence":5,"section_type":"hairpin","sector_name":"Sector 2","start_pct":0.47,"end_pct":0.58,"apex_pct":0.53,"note":"Stabilise the kart early and make the long exit count."},{"name":"Back Section Left","sequence":6,"section_type":"left","sector_name":"Sector 2","start_pct":0.58,"end_pct":0.69,"apex_pct":0.64,"note":"Open the hands and keep the minimum speed up through the middle."},{"name":"Back Section Right","sequence":7,"section_type":"right","sector_name":"Sector 3","start_pct":0.69,"end_pct":0.81,"apex_pct":0.75,"note":"Prepare the final phase and do not over-attack entry."},{"name":"Top Hairpin","sequence":8,"section_type":"hairpin","sector_name":"Sector 3","start_pct":0.81,"end_pct":0.92,"apex_pct":0.87,"note":"This braking zone rewards patience and a clean release."},{"name":"Final Curve","sequence":9,"section_type":"sweeper","sector_name":"Sector 3","start_pct":0.92,"end_pct":0.995,"apex_pct":0.96,"note":"Protect exit quality onto the straight because the lap time carries."}]',
        "aliases_json": '["pfi","pf international"]',
    },
    {
        "id": "kimbolton",
        "name": "Kimbolton",
        "venue": "Stow Longa, Cambridgeshire",
        "postcode": "PE28 0EY",
        "address_json": '["The Old Airfield","Stow Longa","Kimbolton","PE28 0EY"]',
        "google_query": "Kimbolton Kart Circuit Stow Longa Kimbolton PE28 0EY",
        "official_url": "https://www.hkrc.co.uk/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/kimbolton","https://www.hkrc.co.uk/"]',
        "layout_notes": "Compact and technical, rewarding rhythm and clean sequencing.",
        "coaching_focus_json": '["Build linked corners as one sequence.","Stay patient into tighter apexes so exits stay clean.","Consistency is critical because the lap is short."]',
        "corner_notes_json": '["Hairpin-style corners expose over-braking.","Compromise one corner to improve the next.","Throttle hesitation shows up quickly in lap time."]',
        "aliases_json": '["kimbolton"]',
    },
    {
        "id": "fulbeck",
        "name": "Fulbeck",
        "venue": "Stragglethorpe, Lincolnshire",
        "postcode": "LN5 0QZ",
        "address_json": '["Stragglethorpe","Lincolnshire","LN5 0QZ"]',
        "google_query": "Fulbeck Kart Circuit Stragglethorpe Lincolnshire LN5 0QZ",
        "official_url": "https://www.lkrc.uk.com/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/fulbeck","https://www.lkrc.uk.com/"]',
        "layout_notes": "A flatter layout where precision and minimum-speed discipline usually win time.",
        "coaching_focus_json": '["Keep the kart free without scrubbing mid-corner speed.","Focus on repeatable line quality.","Use smooth throttle to stabilise exits."]',
        "corner_notes_json": '["Small steering corrections add up here.","Flatter grip conditions punish impatience.","Wider exits cost more than they first appear."]',
        "aliases_json": '["fulbeck"]',
    },
    {
        "id": "whilton-mill",
        "name": "Whilton Mill",
        "venue": "Daventry, Northamptonshire",
        "postcode": "NN11 2NH",
        "address_json": '["Whilton Locks","Whilton","Daventry","NN11 2NH"]',
        "google_query": "Whilton Mill Whilton Locks Daventry NN11 2NH",
        "official_url": "https://www.whiltonmill.co.uk/",
        "source_urls_json": '["https://www.whiltonmill.co.uk/contact/","https://www.themotorsportnetwork.com/circuits/whilton-mill"]',
        "layout_notes": "Technical and sequence-heavy, with stop-start sections that reward preparation for the next corner.",
        "coaching_focus_json": '["Make hairpin exits count.","Treat bus-stop style sections as one connected sequence.","Avoid over-attacking the first apex of linked corners."]',
        "corner_notes_json": '["Technical complexes reward compromise lines.","Hairpins expose delayed throttle application.","A rushed first phase often hurts the second half of the section."]',
        "aliases_json": '["whilton","whilton mill"]',
    },
    {
        "id": "clay-pigeon",
        "name": "Clay Pigeon",
        "venue": "Wardon Hill, Dorset",
        "postcode": "DT2 9PW",
        "address_json": '["Clay Pigeon Raceway","Wardon Hill","Dorchester","DT2 9PW"]',
        "google_query": "Clay Pigeon Raceway Wardon Hill Dorchester DT2 9PW",
        "official_url": "https://www.claypigeonraceway.com/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/clay-pigeon-raceway","https://www.claypigeonraceway.com/"]',
        "layout_notes": "Fast and flowing, rewarding confidence and keeping rolling speed alive.",
        "coaching_focus_json": '["Carry confidence through the fast sections.","Use braking zones to settle the kart early.","Protect speed through any long loaded corner."]',
        "corner_notes_json": '["Fast direction changes punish hesitation.","Momentum is hard to recover once lost.","Over-driving entry often hurts the entire section."]',
        "aliases_json": '["clay pigeon"]',
    },
    {
        "id": "dunkeswell",
        "name": "Dunkeswell",
        "venue": "Honiton, Devon",
        "postcode": "EX14 4LT",
        "address_json": '["Mansell Raceway","Dunkeswell Aerodrome","Honiton","EX14 4LT"]',
        "google_query": "Mansell Raceway Dunkeswell Aerodrome Honiton EX14 4LT",
        "official_url": "https://www.mansellraceway.com/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/mansell-raceway-dunkeswell","https://www.mansellraceway.com/"]',
        "layout_notes": "A technical stop-start track where low-speed efficiency and rhythm are key.",
        "coaching_focus_json": '["Stay calm into low-speed entries.","Look ahead in linked slow sections.","Use progressive throttle so the kart does not stall on exit."]',
        "corner_notes_json": '["Late rotation costs heavily in slow corners.","The sharper apexes reward early stability.","Low-speed exits decide too much lap time to ignore."]',
        "aliases_json": '["dunkeswell","mansell raceway"]',
    },
    {
        "id": "warden-law",
        "name": "Warden Law",
        "venue": "Sunderland, Tyne and Wear",
        "postcode": "SR3 2PR",
        "address_json": '["Warden Law Motorsport Centre","Sunderland","Tyne and Wear","SR3 2PR"]',
        "google_query": "Warden Law Karting Sunderland SR3 2PR",
        "official_url": "https://kartingnortheast.com/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/warden-law","https://kartingnortheast.com/"]',
        "layout_notes": "Elevation and surface changes make confidence and reference points especially important.",
        "coaching_focus_json": '["Use the gradient changes rather than fighting them.","Protect momentum over the crests.","Stay disciplined in unsettled braking zones."]',
        "corner_notes_json": '["Crests can exaggerate instability on entry.","Blind phases reward consistent markers.","Abrupt inputs are punished more than usual."]',
        "aliases_json": '["warden law"]',
    },
    {
        "id": "gyg",
        "name": "GYG",
        "venue": "Corwen, Conwy",
        "postcode": "LL21 0RU",
        "address_json": '["GYG Karting","Glan Y Gors Park","Corwen","LL21 0RU"]',
        "google_query": "GYG Karting Corwen LL21 0RU",
        "official_url": "https://gygkarting.com/",
        "source_urls_json": '["https://gygkarting.com/","https://kartdirectory.racing/uk/circuit/gyg-karting/"]',
        "layout_notes": "Fast, undulating, and confidence-led with major rewards for commitment and flow.",
        "coaching_focus_json": '["Be brave through the fast sections without over-correcting.","Use the elevation to help rotation.","Keep minimum speed high through the loaded corners."]',
        "corner_notes_json": '["Crests and drops punish second guesses.","Long loaded corners expose excess steering.","A confident line unlocks a lot of lap time here."]',
        "aliases_json": '["gyg","glan y gors"]',
    },
    {
        "id": "shenington",
        "name": "Shennington",
        "venue": "Banbury, Oxfordshire",
        "postcode": "OX15 6NW",
        "address_json": '["Shenington Airfield","Banbury","Oxfordshire","OX15 6NW"]',
        "google_query": "Shenington Kart Circuit Banbury OX15 6NW",
        "official_url": "https://www.sheningtonkrc.co.uk/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/shenington-kart-club","https://www.sheningtonkrc.co.uk/"]',
        "layout_notes": "A technical British layout where traction phases and compromise lines are usually decisive.",
        "coaching_focus_json": '["Build the lap around clean exits.","Keep the kart free enough to rotate without dropping too much speed.","Sequence the linked corners properly."]',
        "corner_notes_json": '["Tighter corners expose over-braking and late release.","Transition corners reward patience on the first phase.","Strong traction phases matter here."]',
        "aliases_json": '["shenington","shennington"]',
    },
    {
        "id": "rowrah",
        "name": "Rowrah",
        "venue": "Frizington, Cumbria",
        "postcode": "CA26 3XU",
        "address_json": '["Cumbria Kart Club","Frizington","Cumbria","CA26 3XU"]',
        "google_query": "Rowrah Kart Circuit Frizington Cumbria CA26 3XU",
        "official_url": "https://www.cumbriakrc.co.uk/",
        "source_urls_json": '["https://www.themotorsportnetwork.com/circuits/rowrah-kart-club","https://www.cumbriakrc.co.uk/"]',
        "layout_notes": "Quick and characterful, with elevation and high-speed confidence playing a big role.",
        "coaching_focus_json": '["Protect speed over the crests and into the next brake zone.","Stay tidy in the high-load corners.","Do not let one unsettled phase ruin the next section."]',
        "corner_notes_json": '["Elevation shifts punish abrupt steering and brake release.","High-speed commitment needs strong reference points.","Confidence through the loaded corners is a major differentiator."]',
        "aliases_json": '["rowrah"]',
    },
]
